[[local-setup]]
Local Setup
-----------

This document will walk you through setting up a locally running Mobile
Control Panel and a local OpenShift cluster using `oc cluster up`. This
guide can be followed for _both_ local development and just a local
installation.

[[requirements]]
Requirements
~~~~~~~~~~~~

* http://docs.ansible.com/ansible/latest/intro_installation.html[Ansible]
>= 2.3.2.0
* https://hub.docker.com/[Docker Hub account]
* https://docs.docker.com/engine/installation/[Docker]
* https://github.com/openshift/origin/releases[oc command line client]
* https://nodejs.org/en/[Node.js] >= 6.10.0

*Note:* On Linux you also need to have the `libselinux-python` package
installed!

For local development, you will need to have a Go environment setup:

[source,sh]
----
export PATH="$PATH:~/go/bin"
----

You will want to add the path permanently to your `.bashrc` or
`.bashprofile`.

[[creating-a-local-cluster]]
Creating a Local Cluster
~~~~~~~~~~~~~~~~~~~~~~~~

[[clone-this-repository]]
Clone this repository
^^^^^^^^^^^^^^^^^^^^^

[source,bash]
----
git clone git@github.com:feedhenry/mcp-standalone.git
----

*Note:* it is a good idea to clone this into a valid $GOPATH, however it
is not essential.

[[install-the-required-ansible-dependencies]]
Install the required ansible dependencies:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,sh]
----
ansible-galaxy install -r ./installer/requirements.yml
----

[[firewall-setup]]
Firewall setup
^^^^^^^^^^^^^^

Next we need to configure Docker registry _and_ ports required as part
of the cluster setup: 

* Linux: Follow steps 2 _and_ 3
https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#linux[here]
* Mac: Follow steps 2 _and_ 3
https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#macos-with-docker-for-mac[here]

For Linux (Fedora) we also need to add an extra port to the `dockerc`
zone:

[source,sh]
----
firewall-cmd --permanent --zone dockerc --add-port 443/tcp
firewall-cmd --reload
----

[[run-the-ansible-installer]]
Run the ansible installer
^^^^^^^^^^^^^^^^^^^^^^^^^

This installer sets up your OpenShift environment with the service catalog and the ansible service broker.

[source,sh]
----
export DOCKERHUB_USERNAME="<username>"
export DOCKERHUB_PASSWORD="<password>"
cd installer/ && ansible-playbook playbook.yml -e "dockerhub_username=$DOCKERHUB_USERNAME" -e "dockerhub_password=$DOCKERHUB_PASSWORD" --ask-become-pass
----

We ask for a DockerHub username and password currently because the
Ansible Service Broker calls Docker APIs to read/load Ansible Playbook
Bundles from a Docker Hub organisation (defaults to `feedhenry`).

This will set up your cluster for you - note that it is possible for
this to fail on the first attempt, as the cluster up check may fail
waiting for the images to be pulled - if this happens, run
`oc cluster down` and execute the playbook again.

*Optional*

You can enable Hawkular metrics by passing `-e 'hawkular_metrics=true'`
as part of your `ansible-playbook` command.

[[local-development-only-run-the-mcp-server-locally]]
(Local Development Only) Run the MCP Server locally
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

For local development, you can run the MCP server locally instead of in
OpenShift. This allows for faster development feedback. To compile & run the
MCP Server execute the following in the root directory of the repo:

[source,sh]
----
cd ..
make run_server NAMESPACE=myproject
----

As we're running the MCP Server outside of OpenShift, it won't know which project the user is in.
The MCP Server needs to know which project so it can look for resources by namespace.
Specifying the `NAMESPACE` var will tell MCP what project to expect resources to be in, and create a service account in that project to access resources.
When using the MCP UI, it is important to stay within this project to avoid unusual behaviour.

In another terminal, bundle the MCP UI extension for OpenShift, watching
for changes. This is required to produce the mcp extension files
referenced in master-config.yaml, and keep them up to date whenever
changed during development.

....
cd ui
grunt local
....

If you see an `ENOSPC` error, you may need to increase the number of
files your user can watch by running this command:

[source,sh]
----
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
----

_NOTE_: Running `grunt local` will _not_ run `uglify` (to help with
local dev), and _will_ include `scripts/config.local.js`. This file is
used to point to a local running MCP server rather than the default of
looking up a Route names `mcp-standalone` and using that as the MCP
server host.

[[creating-mobile-apps]]
Creating Mobile Apps
~~~~~~~~~~~~~~~~~~~~

Once the installer is complete you should be able to access OpenShift at
https://192.168.37.1:8443/console/. You will need to accept the
self-signed certificate.

You can login using `developer` and any password.

Once logged in you should be presented with a `catalog` of services.
To create your first Mobile App:

* Choose the `Mobile` category & `Apps` sub-category.
* Choose `Android App`
* Fill in the required information and continue through the wizard.
** If you are *not* running the MCP Server locally (for local
development), this will provision the MCP Server (first time only)
before creating the Android App.
* You’ll need to accept the self-signed cert for the MCP Server in your
Browser. To do this:
** If running MCP Server locally, go to https://localhost:3001.
** Otherwise, get the route from OpenShift using:
*** `oc get route mcp-standalone -n myproject --template "https://{{.spec.host}} "`
* Visit the route in your browser and accept the cert.
** The page might give a message like `no token provided access denied'.
This is OK as it show’s the cert is now trusted and we’re hitting the
server.
* Back in your Project, click the `Mobile` tab on the left nav. You
should now see the Mobile Overview screen and your Android App.

[[next-steps]]
Next Steps
~~~~~~~~~~

* To contribute to MCP, check out the link:../../README.adoc#contributing[Contributing] section of the README.
* Various link:../../README.adoc#walkthroughs[MCP walkthroughs] are also available.