[[local-setup]]
= Local Setup

This document walks you through setting up:
* a local OpenShift cluster using `oc cluster up`.
* a locally running Mobile Control Panel
You can use this guide for _either_ an installation of Mobile Control Panel or for local development of MCP.

The guide also introduces how to use MCP to create mobile apps. See the other link:../../README.adoc#walkthroughs[MCP walkthroughs]
for more detailed guides.


[[requirements]]
== Requirements

* http://docs.ansible.com/ansible/latest/intro_installation.html[Ansible]
>= 2.3.2.0
* https://hub.docker.com/[Docker Hub account]
* https://docs.docker.com/engine/installation/[Docker]
* https://github.com/openshift/origin/releases[oc command line client] >= 3.7.0-rc0
* https://nodejs.org/en/[Node.js] >= 6.10.0
* `libselinux-python` package (Linux only)
* https://brew.sh[Homebrew] >= 1.3.6 (Mac only)

For local development, you need to set the Go environment :

. Include the Go path:
+
[source,sh]
----
export PATH="$PATH:$GOPATH/bin"
----

. Add the path permanently to your `.bashrc` or `.bashprofile`.

[[creating-a-local-cluster]]
== Creating a Local Cluster

[[clone-this-repository]]
=== Clone this repository

[source,bash]
----
mkdir -p $GOPATH/src/github.com/feedhenry
cd $GOPATH/src/github.com/feedhenry
git clone https://github.com/feedhenry/mcp-standalone
----

*Note:* this clones into your $GOPATH, however it is not essential.

[[install-the-required-ansible-dependencies]]
=== Install the required ansible dependencies:

[source,sh]
----
cd $GOPATH/src/github.com/feedhenry/mcp-standalone
ansible-galaxy install -r ./installer/requirements.yml
----
*Note (macOS):* If you're using `ansible` installed via `pip`, you may need create 
a special folder for ansible-roles and run this command with `--roles-path <ansible-roles-folder-path>`,
or run it with `sudo`. This is because non-root user does not have write access to default ansible roles folder (`/etc/ansible/roles`).

[[firewall-setup]]
=== Configure the Firewall

. Configure the Docker registry _and_ ports required as part
of the cluster setup:
+
* Linux: Follow steps 2 _and_ 3
https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#linux[here]
* Mac: Follow steps 2 _and_ 3
https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#macos-with-docker-for-mac[here]

. For Linux (Fedora) we also need to add an extra port to the `dockerc`
zone:
+
[source,sh]
----
firewall-cmd --permanent --zone dockerc --add-port 443/tcp
firewall-cmd --reload
----

[[run-the-ansible-installer]]
=== Run the MCP Ansible Installer

The installer sets up your OpenShift environment with the service catalog and the ansible service broker.

[source,sh]
----
./installer/install.sh
----

A DockerHub username and password are currently currently required because the
Ansible Service Broker calls Docker APIs to read/load Ansible Playbook
Bundles from a Docker Hub organisation (defaults to `feedhenry`).

NOTE: If the installer fails, run
`make clean` in the repo home directory before running the installer again.

*Optional*

You can enable Hawkular metrics by passing `-e 'hawkular_metrics=true'`
as part of your `ansible-playbook` command.

[[local-development-only-run-the-mcp-server-locally]]
== Run the MCP Server locally (Local Development Only)

You can run the MCP server locally instead of on
OpenShift. This allows for faster development feedback. To compile and run the
MCP Server execute the following in the root directory of the repo:

[source,sh]
----
cd ..
make run_server NAMESPACE=myproject
----

When running the MCP Server outside of OpenShift, it won't know which project the user is in.
The MCP Server needs to know which project so it can look for resources by namespace.
Specifying the `NAMESPACE` var allows MCP to determine which project contains required resources,
and to create a service account in that project to access those resources.
When using the MCP UI, it is important to stay within this project to avoid unusual behaviour.

In another terminal, bundle the MCP UI extension for OpenShift, watching
for changes. This is required to produce the mcp extension files
referenced in master-config.yaml, and keep them up to date whenever
they are changed.

....
cd ui
grunt local
....

If you see an `ENOSPC` error, you may need to increase the number of
files your user can watch by running this command:

[source,sh]
----
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
----

_NOTE_: Running `grunt local` will _not_ run `uglify` (to help with
local dev), and _will_ include `scripts/config.local.js`. This file is
used to point to a local running MCP server rather than the default of
looking up a Route names `mcp-standalone` and using that as the MCP
server host.

[[creating-mobile-apps]]
== Creating Mobile Apps

Once the installer is complete you should be able to access OpenShift at
https://192.168.37.1:8443/console/. You will need to accept the
self-signed certificate.

You can login using `developer` and any password.

Once logged in you should be presented with a `catalog` of services.
To create your first Mobile App:

. Choose the `Mobile` category & `Apps` sub-category.
. Choose `Android App`
. Fill in the required information and continue through the wizard.
+
NOTE: If you are *not* running the MCP Server locally (for local
development), this will provision the MCP Server (first time only)
before creating the Android App.

. Accept the self-signed cert for the MCP Server in your
Browser. To do this:
+
* If running MCP Server locally, go to https://localhost:3001.
* Otherwise, get the route from OpenShift using:
+
`oc get route mcp-standalone -n myproject --template "https://{{.spec.host}} "`

. Visit the route in your browser and accept the cert.
+
NOTE: The page might give a message like `no token provided access denied'.
This is OK as it show’s the cert is now trusted and we’re hitting the
server.
. Back in your Project, click the `Mobile` tab on the left nav. You
should now see the Mobile Overview screen and your Android App.

[[useful-bash-function]]
== Useful Bash Function

The following bash function will allow you to do
....
mcp up
mcp down
....

Add the following to your bash_profile

....
export DOCKERHUB_PASSWORD="supersecret"
export DOCKERHUB_USERNAME="user"
export DOCKERHUB_APBS_ORG="feedhenry"
export TAG=latest

function mcp(){
        if [ "$1" == "up" ]; then
          echo "mcp up"
          cd $GOPATH/src/github.com/feedhenry/mcp-standalone/installer/ && ansible-playbook playbook.yml -e "dockerhub_username=$DOCKERHUB_USERNAME" -e "dockerhub_tag=${TAG:-latest}" -e "dockerhub_password=$DOCKERHUB_PASSWORD" -e "dockerhub_org=$DOCKERHUB_APBS_ORG" --ask-become-pass
       fi
       if [ "$1" == "down" ]; then
         cd $GOPATH/src/github.com/feedhenry/mcp-standalone && make clean
       fi

}
....


[[next-steps]]
== Next Steps

* To contribute to MCP, check out the link:../../README.adoc#contributing[Contributing] section of the README.
* See the other link:../../README.adoc#walkthroughs[MCP walkthroughs].
