---

# TODO: Use Kubernetes Ansible modules here
- name: Login to OpenShift
  shell: oc login -u system:admin
  changed_when: false

- name: Add cluster roles to group
  shell: oc adm policy add-cluster-role-to-group {{ group }} {{ roles | join(' ') }}
  changed_when: false
